"""ACMPC: Transformer-XL actor-critic agents with economic MPC heads."""

from .agent import ActorCriticAgent, ActorCriticState
from .model_config import (
    AgentConfig,
    ActorConfig,
    CriticConfig,
    TransformerConfig,
    CostMapConfig,
    CostMapBounds,
)
from .experiment_config import (
    DiagnosticsSection,
    ExperimentConfig,
    LoggingSection,
    ModelSection,
    MPCSection,
    SamplerSection,
    load_experiment_config,
)
from .models import (
    ActorOutput,
    CriticOutput,
    DirectTransformerActor,
    TransformerActor,
    TransformerCritic,
    TransformerXLBackbone,
    TransformerXLMemories,
)
from .mpc import EconomicMPCConfig, EconomicMPCHead, CostMapMPCHead
from .observation_adapter import ObservationAdapter, ObservationSpec
from .sampling import (
    AbsoluteEnvWrapper,
    VectorEnvManager,
    EnvBatch,
    RolloutBatch,
    RolloutCollector,
)
from .training import (
    DiagnosticsManager,
    DiagnosticsOptions,
    GradientManager,
    GradientManagerConfig,
    MPVEConfig,
    RewardNormalizer,
    RunningMeanStd,
    TrainingBatch,
    TrainingConfig,
    TrainingLoop,
    TrainingMetrics,
    compute_gae,
    rollout_to_training_batch,
)

__all__ = [
    "ActorConfig",
    "CriticConfig",
    "AgentConfig",
    "TransformerConfig",
    "CostMapConfig",
    "CostMapBounds",
    "ExperimentConfig",
    "ModelSection",
    "MPCSection",
    "SamplerSection",
    "DiagnosticsSection",
    "LoggingSection",
    "load_experiment_config",
    "ActorCriticAgent",
    "ActorCriticState",
    "TransformerActor",
    "DirectTransformerActor",
    "TransformerCritic",
    "ActorOutput",
    "CriticOutput",
    "TransformerXLBackbone",
    "TransformerXLMemories",
    "EconomicMPCConfig",
    "EconomicMPCHead",
    "CostMapMPCHead",
    "ObservationAdapter",
    "ObservationSpec",
    "AbsoluteEnvWrapper",
    "VectorEnvManager",
    "EnvBatch",
    "RolloutBatch",
    "RolloutCollector",
    "TrainingBatch",
    "TrainingConfig",
    "TrainingLoop",
    "TrainingMetrics",
    "compute_gae",
    "rollout_to_training_batch",
    "GradientManager",
    "GradientManagerConfig",
    "MPVEConfig",
    "RewardNormalizer",
    "RunningMeanStd",
    "DiagnosticsManager",
    "DiagnosticsOptions",
]
